CREATE DATABASE PEDIDOS;
USE PEDIDOS;

CREATE TABLE ESTADO(
ESTADO_CODIGO CHAR(2) PRIMARY KEY,
ESTADO_NOME VARCHAR(25)
);

CREATE TABLE CLIENTE(
CLIENTE_ID INTEGER(10) PRIMARY KEY,
CLIENTE_NOME CHAR(50),
CLIENTE_END CHAR(50),
CLIENTE_END_CIDADE CHAR(20),
ESTADO_CODIGO CHAR(2),
CLIENTE_END_CEP CHAR(8),
CLIENTE_TELEFONE CHAR(10),
CLIENTE_PERC_DESCONTO DECIMAL(2,0),
FOREIGN KEY(ESTADO_CODIGO) REFERENCES ESTADO(ESTADO_CODIGO)
);

CREATE TABLE UE_PRODUTO(
UE_PRODUTO_COD CHAR(3) PRIMARY KEY,
UE_PRODUTO_DESCR VARCHAR(50)
);

CREATE TABLE PRODUTO(
PRODUTO_CODIGO SMALLINT(6) PRIMARY KEY,
PRODUTO_NOME CHAR(40),
PRODUTO_PRECO DOUBLE(5,2),
UE_PRODUTO_COD CHAR (3),
FOREIGN KEY(UE_PRODUTO_COD) REFERENCES UE_PRODUTO(UE_PRODUTO_COD)
);

CREATE TABLE PEDIDO(
PEDIDO_IDENTIFICACAO INTEGER(11) PRIMARY KEY,
PEDIDO_TIPO ENUM('A VISTA', 'A PRAZO 30 DIA...'),
CLIENTE_ID INTEGER(10),
PEDIDO_DATA_ENTRADA DATE,
PEDIDO_VALOR_TOTAL DECIMAL(7,2),
PEDIDO_DESCONTO DECIMAL(7,2),
PEDIDO_DT_EMBARQUE DATE,
FOREIGN KEY(CLIENTE_ID) REFERENCES CLIENTE(CLIENTE_ID)
);

CREATE TABLE ITEM(
PEDITO_IDENTIFICACAO INTEGER(11) PRIMARY KEY,
PRODUTO_CODIGO SMALLINT(6),
ITEM_QUANTIDADE SMALLINT(6),
ITEM_VALOR_UNITARIO DOUBLE(5,2),
ITEM_VALOR_TOTAL DOUBLE(5,2),
FOREIGN KEY(PRODUTO_CODIGO) REFERENCES PRODUTO(PRODUTO_CODIGO)
);

CREATE TABLE PRODUTO_CC_6A(
PRODUTO_CC_6A_NOME VARCHAR(40),
PRODUTO_CC_6A_PRECO DOUBLE(5,2)
);

CREATE TABLE UE_PRODUTO_CC_6A(
UE_PRODUTO_CC_6A_DESCR CHAR(50)
);

ALTER TABLE PRODUTO_CC_6A
ADD COLUMN PRODUTO_CC_6A_CODIGO SMALLINT NOT NULL PRIMARY KEY FIRST;

ALTER TABLE UE_PRODUTO_CC_6A
ADD COLUMN UE_PRODUTO_CC_6A_CODIGO CHAR(3) NOT NULL PRIMARY KEY FIRST;

ALTER TABLE PRODUTO_CC_6A
ADD COLUMN UE_PRODUTO_CC_6A_CODIGO CHAR(3) NOT NULL;

ALTER TABLE PRODUTO_CC_6A ADD FOREIGN KEY (UE_PRODUTO_CC_6A_CODIGO) REFERENCES UE_PRODUTO_CC_6A(UE_PRODUTO_CC_6A_CODIGO);

CREATE UNIQUE INDEX INDICE_PRODUTO_CC_6A ON PRODUTO_CC_6A(PRODUTO_CC_6A_NOME);